#!/usr/bin/env python
#a more streamlined version of showipbgp from wk2

#initial input provided by instructor
entry1 = "*  1.0.192.0/18   157.130.10.233        0 701 38040 9737 i"
entry2 = "*  1.1.1.0/24       157.130.10.233        0 701 1299 15169 i"
entry3 = "*  1.1.42.0/24     157.130.10.233        0 701 9505 17408 2.1465 i"
entry4 = "*  1.0.192.0/19   157.130.10.233        0 701 6762 6762 6762 6762 38040 9737 i"

entry_list = []

for string in entry1,entry2,entry3,entry4:
    entry_list.append(string.split(" "))

#print headings left alligned with 20 spaces between columns
print "%-20s %-20s" % ("ip_prefix","as_path")

#create empty list that holds index numbers
entry_list_index = []
#find index number that starts with 701 for each entry list and add it to entry_list_index
for i in range(len(entry_list)):
    entry_list_index.append(entry_list[i].index('701'))

#print ip_prefix and AS_PATH value only starting at 701
for i in range(len(entry_list)):
    print "%-20s %-20s" % (entry_list[i][2], entry_list[i][entry_list_index[i]:-1])
